---
platform: linux

image: docker:///golang#1.7-alpine

inputs:
- name: gopath-tested
- name: version

outputs:
- name: build-output/build

run:
  path: gopath-tested/src/github.com/jghiloni/cf-apptree/ci/tasks/do-build.sh
